name: 'CppSDKReleaseAssetDownloader'
description: 'Download specific C++ SDK release asset.'
inputs:
  url:
    description: 'C++ SDK release URL.'
    required: true
  tag:
    description: 'Release tag of C++ SDK release.'
    required: true
  asset_suffix:
    description: 'The suffix of the C++ SDK asset defining the platform.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download C++ Windows
      run: |
        $Env:INPUT_URL = "${{ inputs.url }}"
        $Env:INPUT_TAG = "${{ inputs.tag }}"
        $Env:INPUT_ASSET_NAME = "cppsdk-${{ inputs.tag }}-${{ inputs.asset_suffix }}"
        ./.github/actions/download_cppsdk/powershell/download_cppsdk.ps1
      shell: powershell
